### ISSUE TITLE
Error connecting to cosmetica servers

### ISSUE THREAD

**Issue by MoonSkulll** [Cosmetica-cc/Cosmetica#116] opened 2023-09-02 20:25 UTC
![image](https://github.com/Cosmetica-cc/Cosmetica/assets/143906882/d2c101a5-68fc-4b03-8aa8-459bbaccf636)
When I try to connect to the server to use the cosmetics, it just goes to this. I have a normal, payed for, minecraft account and my internet is actually really good. I don't know why it's not working? I'm playing a modpack called DarkRPG, 1.20.1, version 7.2.6 if that helps!

**Comment by zVort3X** [comment] 2023-09-02 21:07
same here, i think the servers are down

**Comment by valoeghese** [comment] 2023-10-24 00:17
closed as duplicate of #110 
just cleaning up so we have one issue tracking every known bug

**Closed by valoeghese** 2023-10-24 00:17 UTC
Labels: bug, duplicate, fixed in dev
