### ISSUE TITLE
Mod not loading, giving incorrect "bad connection/cracked minecraft" error

### ISSUE THREAD

**Issue by bvnniz** [Cosmetica-cc/Cosmetica#119] opened 2023-10-08 18:27 UTC
i play on a 1.20.1 fabric server with my friends and we just recently stopped being able to see our cosmetics.. and trying to open the settings to customize anything will either permanently be stuck "connecting to cosmetica servers" or will eventually time out and give me the "error connecting to cosmetica servers / we couldn't authenticate your account! this could be because you're using a cracked minecraft account or your internet isn't working." screen (both of which shown below). 

![image](https://github.com/Cosmetica-cc/Cosmetica/assets/111303383/e39123cf-dbdf-402a-ae59-3bbe09c9decc)

![image](https://github.com/Cosmetica-cc/Cosmetica/assets/111303383/afe3a8da-93de-4087-a44c-cb086ff86fb6)

i dont know if this is a problem with the cosmetica servers themselves or if the mod is just broken. we have not been having problems until this point so idk what changed :( 

 - OS: win10
 - MC version: 1.20.1
 - Mod version: 1.2.5

**Comment by valoeghese** [comment] 2023-10-24 00:14
Closed as duplicate of #110

**Closed by valoeghese** 2023-10-24 00:14 UTC
Labels: duplicate
